import { NextApiRequest, NextApiResponse } from 'next';
import { connectToDatabase } from '../../../lib/mongodb';
import { requireAuth } from '../../../utils/serverAuth';
import connectDB from '../../../utils/db';
import User from '../../../models/User';

function buildMessage(userName: string, location: string, triggerMethod: string, emotion: string, fearLevel: number, lat?: number, lon?: number): string {
  const mapsLink = lat && lon ? `https://maps.google.com/?q=${lat},${lon}` : null;
  const currentTime = new Date().toLocaleString('en-US', { 
    month: 'short', 
    day: 'numeric', 
    year: 'numeric', 
    hour: '2-digit', 
    minute: '2-digit',
    hour12: true
  });

  let message = `*URGENT: Emergency Assistance Required*\n\n`;
  message += `Dear Emergency Contact,\n\n`;
  message += `This is an automated alert from the SOS Emergency Response System. Your immediate assistance is required.\n\n`;
  message += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;
  message += `*INCIDENT DETAILS*\n`;
  message += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n`;
  message += `*Person Requesting Help:* ${userName}\n`;
  message += `*Current Location:* ${location}\n`;
  
  if (mapsLink) {
    message += `*Precise Location:* ${mapsLink}\n`;
  }
  
  message += `*Alert Trigger Method:* ${triggerMethod}\n`;
  
  if (emotion && emotion !== 'unknown') {
    message += `*Emotional State:* ${emotion} (Confidence: ${fearLevel}%)\n`;
  }
  
  message += `*Date & Time:* ${currentTime}\n\n`;
  message += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;
  message += `*RECOMMENDED ACTION*\n`;
  message += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n`;
  message += `1. Contact the person immediately\n`;
  message += `2. Verify their safety status\n`;
  message += `3. If unreachable, consider contacting local emergency services\n\n`;
  message += `_This alert was generated by the SOS Emergency Response System._`;

  return message;
}

type ContactResult = { name: string; phone: string; channel: string; status: string; sid?: string; error?: string };

async function sendAlerts(
  contacts: Array<{ name: string; phone: string }>,
  message: string
): Promise<ContactResult[]> {
  const twilio = (await import('twilio')).default;
  const client = twilio(process.env.TWILIO_ACCOUNT_SID!, process.env.TWILIO_AUTH_TOKEN!);

  const whatsappFrom = process.env.TWILIO_WHATSAPP_FROM;
  const results: ContactResult[] = [];

  // Validate Twilio configuration
  if (!whatsappFrom) {
    console.error('❌ TWILIO_WHATSAPP_FROM not configured');
    return contacts.map(c => ({
      name: c.name,
      phone: c.phone,
      channel: 'whatsapp',
      status: 'failed',
      error: 'Twilio WhatsApp not configured (TWILIO_WHATSAPP_FROM missing)'
    }));
  }

  console.log(`📤 Attempting to send WhatsApp alerts to ${contacts.length} contact(s)`);
  console.log(`📌 Using WhatsApp number: ${whatsappFrom}`);

  for (const contact of contacts) {
    // Sanitize phone number: remove spaces, dashes, parentheses, etc.
    // Keep only + and digits
    const phone = contact.phone.trim().replace(/[\s\-().]/g, '');

    // Ensure it starts with +
    const cleanPhone = phone.startsWith('+') ? phone : `+${phone}`;

    try {
      // Validate phone format
      if (!cleanPhone.match(/^\+\d{10,15}$/)) {
        console.warn(`⚠️ Invalid phone format after sanitization: ${contact.phone} → ${cleanPhone}`);
      }

      console.log(`📍 Sending to ${contact.name} (${contact.phone} → ${cleanPhone})...`);

      const msg = await client.messages.create({
        body: message,
        from: whatsappFrom,
        to: `whatsapp:${cleanPhone}`,
      });
      
      console.log(`✅ WhatsApp sent to ${contact.name} (${cleanPhone}) — SID: ${msg.sid}`);
      results.push({ name: contact.name, phone: cleanPhone, channel: 'whatsapp', status: 'sent', sid: msg.sid });
    } catch (err: any) {
      console.error(`❌ WhatsApp failed for ${contact.name} (${cleanPhone})`);
      console.error(`   Error: ${err.message}`);
      console.error(`   Code: ${err.code || 'N/A'}`);
      console.error(`   Details:`, err);
      
      results.push({ 
        name: contact.name, 
        phone: cleanPhone, 
        channel: 'whatsapp', 
        status: 'failed', 
        error: `${err.code || 'ERROR'}: ${err.message}` 
      });
    }
  }

  console.log(`📊 Send Results Summary: ${results.filter(r => r.status === 'sent').length}/${contacts.length} successful`);
  return results;
}

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ message: 'Method not allowed' });
  }

  try {
    const user = await requireAuth(req, res);
    if (!user) return;

    const { db } = await connectToDatabase();
    await connectDB();

    const userDoc = await (User as any).findById(user.id).select('contacts');
    if (!userDoc?.contacts?.length) {
      return res.status(400).json({
        success: false,
        message: 'No emergency contacts configured. Please add contacts in your profile.',
      });
    }

    const { location, emotion, fearLevel, triggerMethod, detectedKeyword, timestamp, lat, lon } = req.body;

    const alertData = {
      userId: user.id,
      userEmail: user.email,
      userName: user.name,
      contacts: userDoc.contacts.map((c: any) => ({ name: c.name, phone: c.phone, relationship: c.relationship })),
      location: location || 'Location unavailable',
      emotion: emotion || 'unknown',
      fearLevel: fearLevel || 0,
      triggerMethod: triggerMethod || 'Manual',
      detectedKeyword: detectedKeyword || null,
      createdAt: new Date(timestamp || Date.now()),
      status: 'pending',
    };

    const result = await db.collection('emergency_alerts').insertOne(alertData);
    console.log(`🚨 Emergency alert for ${user.email} → ${userDoc.contacts.length} contact(s)`);

    const message = buildMessage(
      user.name, alertData.location, alertData.triggerMethod,
      alertData.emotion, alertData.fearLevel, lat, lon
    );

    // Check Twilio configuration
    const hasSID = !!process.env.TWILIO_ACCOUNT_SID;
    const hasToken = !!process.env.TWILIO_AUTH_TOKEN;
    const hasWhatsappFrom = !!process.env.TWILIO_WHATSAPP_FROM;
    
    console.log(`🔧 Twilio Config Check:`);
    console.log(`   ✓ TWILIO_ACCOUNT_SID: ${hasSID ? 'Set' : '❌ MISSING'}`);
    console.log(`   ✓ TWILIO_AUTH_TOKEN: ${hasToken ? 'Set' : '❌ MISSING'}`);
    console.log(`   ✓ TWILIO_WHATSAPP_FROM: ${hasWhatsappFrom ? 'Set' : '❌ MISSING'}`);

    const twilioConfigured = hasSID && hasToken && hasWhatsappFrom;

    let sendResults: ContactResult[] | { name: string; phone: string; status: string }[];

    if (twilioConfigured) {
      console.log('✅ Twilio configured — sending real alerts');
      sendResults = await sendAlerts(userDoc.contacts, message);
    } else {
      console.log('⚠️ Twilio not fully configured — simulating');
      console.log(`   Missing: ${[!hasSID ? 'ACCOUNT_SID' : '', !hasToken ? 'AUTH_TOKEN' : '', !hasWhatsappFrom ? 'WHATSAPP_FROM' : ''].filter(Boolean).join(', ')}`);
      sendResults = userDoc.contacts.map((c: any) => ({ 
        name: c.name, 
        phone: c.phone, 
        status: 'simulated',
        error: 'Twilio not configured'
      }));
    }

    await db.collection('emergency_alerts').updateOne(
      { _id: result.insertedId },
      { $set: { status: 'sent', sendResults, sentAt: new Date() } }
    );

    const sentCount = (sendResults as any[]).filter(r => r.status === 'sent').length;
    const whatsappCount = (sendResults as ContactResult[]).filter(r => r.status === 'sent' && r.channel === 'whatsapp').length;
    const smsCount = (sendResults as ContactResult[]).filter(r => r.status === 'sent' && r.channel === 'sms').length;

    return res.status(200).json({
      success: true,
      message: `Alert sent to ${sentCount}/${userDoc.contacts.length} contact(s) — WhatsApp: ${whatsappCount}, SMS: ${smsCount}`,
      alertId: result.insertedId,
      contactsNotified: userDoc.contacts.length,
      sendResults,
    });
  } catch (error) {
    console.error('❌ Error sending emergency alert:', error);
    return res.status(500).json({
      success: false,
      message: 'Internal server error',
      error: error instanceof Error ? error.message : 'Unknown error',
    });
  }
}
